"use strict";
$('.call-modal').click(function () {
    $('.modal').show()
});
$('.modal-close').click(function () {
    $('.modal').hide()
});

console.log('Hello world');
let Myfirstchild = 'Freelance';
console.log('Myfirstchild');
let Turpal = 23;
let TUUUUUT = 26;
Turpal = TUUUUUT;
console.log(Turpal);
let User = 'Коля';
let Username = 'Вася';
User = Username;
console.log(User);
let Top;
console.log(typeof Top);
console.log(Top);
let block = document.querySelector('.block');
console.log(block);
let title = 60 > 59;
console.log(title);
